# Generated by Django 3.1.7 on 2021-05-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0014_auto_20210507_2038'),
        ('intentos', '0003_auto_20210507_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intento',
            name='abierto',
        ),
        migrations.AlterField(
            model_name='intentopregunta',
            name='correcto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='intentopregunta',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.opcion'),
        ),
    ]
