# Generated by Django 3.1.7 on 2021-05-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentos', '0005_auto_20210509_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='puntos',
            field=models.FloatField(default=0),
        ),
    ]
