# Generated by Django 3.1.7 on 2021-04-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombres'),
        ),
    ]
