# Generated by Django 3.1.7 on 2021-04-29 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_auto_20210428_1950'),
        ('intentos', '0001_initial'),
        ('users', '0003_auto_20210428_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puntaje_total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ScoreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.FloatField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.evaluacion')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intentos.intento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
