# Generated by Django 3.1.7 on 2021-04-30 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210428_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScoreUser',
        ),
    ]
