# Generated by Django 3.1.7 on 2021-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rango',
            field=models.CharField(default='Practicante', editable=False, max_length=50),
        ),
    ]
