# Generated by Django 3.1.7 on 2021-05-05 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_codigo_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguirUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidos', to=settings.AUTH_USER_MODEL, verbose_name='Seguidores')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguir Usuario',
                'verbose_name_plural': 'Seguir Usuarios',
                'unique_together': {('seguido', 'seguidor')},
            },
        ),
    ]
