# Generated by Django 3.1.7 on 2021-05-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seguirusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='puntaje_total',
        ),
    ]
