# Generated by Django 3.1.7 on 2021-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_puntaje_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.TextField(default='', max_length=250),
        ),
    ]
