# Generated by Django 3.1.7 on 2021-06-16 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario_notificacion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_notificacion', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
