# Generated by Django 3.1.7 on 2021-06-16 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210615_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='usuario_notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_notificacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
