# Generated by Django 3.1.7 on 2021-06-16 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210615_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
    ]
