# Generated by Django 3.1.7 on 2021-06-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_puntos_totales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='puntos_totales',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
    ]
