# Generated by Django 3.1.7 on 2021-04-29 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoria')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('dificultad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AlterModelOptions(
            name='puntuardificultad',
            options={'verbose_name': 'Calificar Dificultad', 'verbose_name_plural': 'Calificar Dificultad'},
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='dificultad_ponderada',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='puntuardificultad',
            unique_together={('evaluacion', 'usuario')},
        ),
    ]
