# Generated by Django 3.1.7 on 2021-04-29 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_auto_20210428_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.categoria', verbose_name='Categorias'),
        ),
    ]
