# Generated by Django 3.1.7 on 2021-04-29 16:34

import apps.evaluaciones.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_evaluacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='dificultad',
            field=models.IntegerField(validators=[apps.evaluaciones.validators.dificultadminmax]),
        ),
    ]
