# Generated by Django 3.1.7 on 2021-04-30 01:58

import apps.evaluaciones.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0005_auto_20210429_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorarEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(validators=[apps.evaluaciones.validators.dificultadminmax])),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valorar', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Votar Evaluación',
                'verbose_name_plural': 'Votar Evaluaciones',
                'unique_together': {('evaluacion', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='SeguirEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguir', to='evaluaciones.evaluacion', verbose_name='Evaluación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguir Evaluación',
                'verbose_name_plural': 'Seguir Evaluaciones',
                'unique_together': {('evaluacion', 'usuario')},
            },
        ),
    ]
