# Generated by Django 3.1.7 on 2021-05-01 19:04

import apps.evaluaciones.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0006_seguirevaluacion_valorarevaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorarevaluacion',
            options={'verbose_name': 'Valorar Evaluación', 'verbose_name_plural': 'Valorar Evaluaciones'},
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Subcategoria')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('dificultad', models.IntegerField(validators=[apps.evaluaciones.validators.dificultadminmax])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'SubCategoria',
                'verbose_name_plural': 'SubCategorias',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.subcategoria', verbose_name='SubCategorias'),
        ),
    ]
