# Generated by Django 3.1.7 on 2021-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0009_auto_20210501_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='requisitos_minimos',
            field=models.TextField(default=''),
        ),
    ]
