# Generated by Django 3.1.7 on 2021-05-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0010_evaluacion_requisitos_minimos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='evaluaciones.categoria', verbose_name='Categoria'),
        ),
    ]
