# Generated by Django 3.1.7 on 2021-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0012_auto_20210506_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=150),
        ),
    ]
