# Generated by Django 3.1.7 on 2021-05-08 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0013_auto_20210506_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificardificultad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dificultad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=200, verbose_name='Opcion'),
        ),
        migrations.AlterField(
            model_name='valorarevaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valorar', to=settings.AUTH_USER_MODEL),
        ),
    ]
