# Generated by Django 3.1.7 on 2021-05-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0014_auto_20210507_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='descripcion',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='requisitos_minimos',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='descripcion',
            field=models.TextField(max_length=250, verbose_name='Descripción'),
        ),
    ]
